title: "Sadie's AI & Data Science!"
description: "Here do I record my study."
author: "Sadie"
email: sh.sadiehan@gmail.com
baseurl: "" # 리포지토리 이름이 URL에 포함되지 않으면 빈 값
url: "https://hanmind.github.io" # 깃허브 페이지 주소

remote_theme: "jeffreytse/jekyll-theme-yat"

paginate: 5
permalink: /:title/

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

yat:
  theme_color: "light" # 또는 "dark"
  header:
    title: "Sadie's AI & Data Science!"
    slogan: "Digital well-being and HCI adventures"
  footer:
    copyright: "© 2025 Sadie. All rights reserved."
    github: "https://github.com/hanmind"
    email: "sh.sadiehan@gmail.com"
